server:
  port: 8090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicate:
            - path: /api/**
        - id: car-service
            uri: lb://car-service
            predicate:
              - path: /api/**
        - id: bike-service
            uri: lb://bike-service
            predicate:
              - path: /api/**